# Generated by Django 4.0.3 on 2022-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campin', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.webp', upload_to='images/'),
        ),
    ]
