# Generated by Django 4.0.3 on 2022-04-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campin', '0005_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycampin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycampins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
